### ISSUE TITLE
SQL Exceptions in JPA branch

### ISSUE THREAD

**Issue by SkylerMime** [primefaces/primefaces-test#430]
# My Environment

Ubuntu 22.04.3 LTS,
    running on Windows Subsystem for Linux (WSL)
OpenJDK 17.0.12

# What I did

- I cloned the repo
- switched to the JPA branch
- ran `mvn clean jetty:run`
- Opened localhost:8080 in the browser

# Result

The table does render and can be sorted, but any attempt to use the filters along the top causes all rows to disappear and throws exceptions:

```
ERROR: incompatible data type in operation in statement [select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?]
Sep 17, 2024 12:01:39 PM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/test.xhtml]
org.hibernate.exception.SQLGrammarException: could not prepare statement [incompatible data type in operation in statement [select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?]] [select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?]
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:66)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:191)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:153)
        at org.hibernate.sql.exec.internal.StandardStatementCreator.createStatement(StandardStatementCreator.java:49)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:235)
        at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:171)
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.<init>(JdbcValuesResultSetImpl.java:74)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValuesSource(JdbcSelectExecutorStandardImpl.java:355)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:137)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:102)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.executeQuery(JdbcSelectExecutor.java:91)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:165)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:152)
<...many more>
org.hibernate.engine.jdbc.internal.StatementPreparerImpl$4.doPrepare(StatementPreparerImpl.java:151)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:180)
        ... 73 more
Caused by: org.hsqldb.HsqlException: incompatible data type in operation
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.FunctionSQL.resolveTypes(Unknown Source)
        at org.hsqldb.ExpressionLike.resolveTypes(Unknown Source)
        at org.hsqldb.QuerySpecification.resolveExpressionTypes(Unknown Source)
        at org.hsqldb.QuerySpecification.resolveTypesPartOne(Unknown Source)
        at org.hsqldb.QueryExpression.resolve(Unknown Source)
        at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
        at org.hsqldb.ParserCommand.compilePart(Unknown Source)
        at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
        at org.hsqldb.Session.compileStatement(Unknown Source)
        at org.hsqldb.StatementManager.compile(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 77 more
```

**Comment by melloware** [comment]
weird its working fine for me.

```
C:\dev\primetek\primefaces-test>mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\tools\apache-maven-3.9.9
Java version: 17.0.11, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

Maybe something different about Linux?

**Comment by melloware** [comment]
Werid works for me under WSL2 also.

```
melloware@mellowarep16:~/primefaces-test$ mvn --version
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /opt/maven
Java version: 17.0.9, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.153.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by melloware** [comment]
Why is it doing an UPPERCASE on a decimal column?  

```
select count(tj1_0.id) from TestJpa tj1_0 where upper(tj1_0.decimalCol) like ?
```

**Comment by melloware** [comment]
I see its when you filter on a Decimal Column its doing a String filter.

**Comment by melloware** [comment]
cc @FlipWarthog

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces/primefaces-test/commit/12dcfd920542eed2e5e11761b161d0c9b7e37030

Those are not string columns so you need to do `filterMatchMode="gt"` or something that supports numerics.

**Comment by FlipWarthog** [comment]
> Fixed with commit: https://github.com/primefaces/primefaces-test/commit/12dcfd920542eed2e5e11761b161d0c9b7e37030
> 
> Those are not string columns so you need to do `filterMatchMode="gt"` or something that supports numerics.

I think it's the case insensitive setting too:

https://github.com/primefaces/primefaces-test/blob/jpa/src%2Fmain%2Fjava%2Forg%2Fprimefaces%2Ftest%2FTestView.java#L34

**Comment by tandraschko** [comment]
Shouldnt equals just work?

**Comment by melloware** [comment]
yeah its because `caseInsensitive="true"` so it was doing an `UPPER()` on the filters. Probably need a way of making case smarter.

**Comment by tandraschko** [comment]
Ah i see

**Comment by melloware** [comment]
I will investigate and open a PF ticket to see if its possible to prevent doing an UPPER on a Number column
